#include <stdlib.h>
#include <stdio.h>
#include <wchar.h>
#include <errno.h>
#include "xlocale.h"
#include "xstdlib.h"

int main() {
	// 1. Test xrand
	xinit_console_utf8();
	size_t size = 10;
	unsigned int flags = 256; // random byte values
	void* buffer = xrand(size, flags);
	if (!buffer) {
		perror("xrand failed");
	} else {
		printf("xrand generated bytes: ");
		for (size_t i = 0; i < size; i++)
			printf("%u ", ((unsigned char*)buffer)[i]);
		printf("\n");
		free(buffer);
	}

	// 2. Test xwcstombs and xmbstowcs
	const wchar_t *wtext = L"Hello, 世界!"; // output: xwcstombs: Hello, ä¸ç! in windows fix it
	char *mbs = xwcstombs(wtext);
	if (mbs) {
		printf("xwcstombs: %s\n", mbs);

		wchar_t *wcs2 = xmbstowcs(mbs);
		if (wcs2) {
			wprintf(L"xmbstowcs: %ls\n", wcs2);
			free(wcs2);
		} else {
			perror("xmbstowcs failed");
		}

		free(mbs);
	} else {
		perror("xwcstombs failed");
	}

	// 3. Test xsystem
	printf("Testing xsystem:\n");
	int ret = xsystem("echo %ls", L"Hello from xwsystem");
	printf("xsystem returned: %d\n", ret);

	// 4. Test xwsystem
	wprintf(L"Testing xwsystem:\n");
	ret = xwsystem(L"echo %ls", L"Hello from xwsystem");
	wprintf(L"xwsystem returned: %d\n", ret);

	// 5. Test xperror
	errno = ENOMEM;
	printf("Testing xperror:\n");
	xperror("This is a test error");

	// 6. Test xwperror
	errno = EFBIG;
	wprintf(L"Testing xwperror:\n");
	xwperror(L"This is a wide test error");

	return 0;
}
